services:

  ### WORKSPACE ############################################
  workspace:
    container_name: workspace
    build:
      context: ./workspace
      args:
        - DOCKER_PHP_VERSION=${PHP_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    image: workspace:${PHP_VERSION}
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_BROWSERSYNC_HOST_PORT}:3000"
      - "${WORKSPACE_BROWSERSYNC_UI_HOST_PORT}:3001"
      - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT}:8080"
      - "${WORKSPACE_VUE_CLI_UI_HOST_PORT}:8000"
      - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT}:4200"
      - "${WORKSPACE_VITE_PORT}:5173"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - docker-in-docker:/certs/client
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME=${PHP_FPM_FAKETIME}
      - TZ=${TIMEZONE}
    networks:
      - backend
      - frontend
    links:
      - docker-in-docker

  ### NGINX Server #########################################
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ./public/:/usr/share/nginx/html/
    working_dir: ${APP_CODE_PATH_CONTAINER}
    environment:
      - TZ=${TIMEZONE}
    networks:
      - frontend
      - backend
    depends_on:
      - php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ### PHP-FPM ##############################################
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        - DOCKER_PHP_VERSION=${PHP_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    image: php-fpm:${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./public/:/usr/share/nginx/html/
      - docker-in-docker:/certs/client
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME=${PHP_FPM_FAKETIME}
      - TZ=${TIMEZONE}
    networks:
      - backend
    depends_on:
      - workspace
    links:
      - docker-in-docker

  ### MySQL ################################################
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - backend

  ### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: phpmyadmin
    build: ./phpmyadmin
    image: phpmyadmin:${PMA_VERSION}
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    networks:
      - frontend
      - backend
    depends_on:
      - "${PMA_DB_ENGINE}"

  ### Redis ################################################
  redis:
    container_name: redis
    build: ./redis
    image: redis:${REDIS_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  ### Docker-in-Docker #####################################
  docker-in-docker:
    container_name: docker-in-docker
    image: docker:20.10-dind
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    privileged: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - backend

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}